import React, { useRef, useState } from 'react';
import { Button, Modal, Spinner } from 'react-bootstrap';
import { uploadSyllabus } from '../../functions/uploadSyllabus';

// Note for CS571 Staff: This page was generated by AI. 
// This was to vastly improve the user experience design so that they could see progress 
function readFileAsDataUrl(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = () => resolve(reader.result);
        reader.onerror = () => reject(reader.error);

        reader.readAsDataURL(file);
    });
}

export default function UploadSyllabusModal({ show, onHide, onSyllabusAdded }) {
    const fileInputRef = useRef(null);
    const [isUploading, setIsUploading] = useState(false);

    const handleUpload = async () => {
        const fileInput = fileInputRef.current;
        const file = fileInput?.files?.[0];

        if (!file) {
            alert('Please select a file first.');
            return;
        }

        try {
            setIsUploading(true);

            const pdfDataUrl = await readFileAsDataUrl(file);
            const data = await uploadSyllabus(fileInput);

            if (data) {
                onSyllabusAdded({
                    ...data,
                    uploaded_pdf_name: file.name,
                    uploaded_pdf_data_url: pdfDataUrl
                });

                fileInput.value = '';
                onHide();
                alert('Syllabus added successfully!');
            }
        } catch (error) {
            console.error('Error uploading syllabus:', error);
            alert(`Error uploading syllabus: ${error.message}`);
        } finally {
            setIsUploading(false);
        }
    };

    return (
        <Modal
            show={show}
            onHide={isUploading ? undefined : onHide}
            backdrop={isUploading ? 'static' : true}
            keyboard={!isUploading}
        >
            <Modal.Header closeButton>
                <Modal.Title>Upload Syllabus</Modal.Title>
            </Modal.Header>

            <Modal.Body>
                <input
                    ref={fileInputRef}
                    type="file"
                    id="syllabus-upload"
                    name="syllabus-upload"
                    accept=".pdf"
                    className="form-control"
                    disabled={isUploading}
                />

                {isUploading && (
                    <div className="d-flex align-items-center gap-2 mt-3">
                        <Spinner animation="border" size="sm" />
                        <span>Uploading syllabus...</span>
                    </div>
                )}
            </Modal.Body>

            <Modal.Footer>
                <Button variant="secondary" onClick={onHide} disabled={isUploading}>
                    Cancel
                </Button>

                <Button variant="primary" onClick={handleUpload} disabled={isUploading}>
                    {isUploading ? 'Uploading...' : 'Upload'}
                </Button>
            </Modal.Footer>
        </Modal>
    );
}
